# Generated by Django 4.2.7 on 2025-10-10 04:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('recruiting_link', models.URLField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Resume Screening'), ('coding_test', 'Coding Test'), ('technical_interview', 'Technical Interview'), ('cultural_fit', 'Cultural Fit Interview'), ('final_interview', 'Final Interview'), ('offer', 'Offer Received'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='applied', max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('coding_test', 'Coding Test'), ('technical_interview', 'Technical Interview'), ('cultural_fit', 'Cultural Fit Interview'), ('final_interview', 'Final Interview'), ('general', 'General Notes')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.position')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('coding_test', 'Coding Test'), ('technical_interview', 'Technical Interview'), ('cultural_fit', 'Cultural Fit Interview'), ('final_interview', 'Final Interview'), ('phone_screen', 'Phone Screen'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.position')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
