# Generated by Django 4.2.7 on 2025-10-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_position_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewevent',
            name='end_datetime',
        ),
        migrations.AddField(
            model_name='interviewevent',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='interviewevent',
            name='meeting_type',
            field=models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote')], default='on-site', max_length=20),
        ),
    ]
